export const workflowSteps = [
  {
    label: "Compare",
    description:
      "Inspect PostgreSQL database state against the desired state kept in the repository.",
  },
  {
    label: "Capture",
    description:
      "Store selected database objects and reference data as durable files for review.",
  },
  {
    label: "Review",
    description:
      "See object-level and row-level differences before release artifacts are prepared.",
  },
  {
    label: "Generate",
    description:
      "Create review-only release SQL artifacts without applying them to the database.",
  },
];

export const screenshotPlaceholders = [
  "Schema comparison",
  "Object Diff",
  "Reference Data Diff",
  "Release Plan",
];

export const safetyCommitments = [
  {
    title: "Database execution stays outside DbState",
    summary:
      "DbState does not directly apply generated SQL or execute generated release artifacts.",
    detail:
      "Users review and execute approved SQL using their normal database release process outside DbState.",
    label: "controlled handoff",
  },
  {
    title: "Destructive changes remain manual-review cases",
    summary:
      "Destructive SQL is not generated by default, and database-only or changed objects may remain manual-review cases.",
    detail:
      "DbState avoids pretending that every database difference can be safely automated.",
    label: "manual review",
  },
  {
    title: "Repository and Git changes remain explicit",
    summary:
      "Repository file writes occur only through explicit user workflows.",
    detail:
      "DbState does not automatically add, commit, push, pull, fetch, or tag. The user retains control of Git history and release handoff.",
    label: "user remains in control",
  },
];

export const safetyTechnicalBoundaries = [
  "No direct database apply",
  "No generated SQL execution",
  "No destructive SQL generation by default",
  "No automatic Git add, commit, push, pull, fetch, or tag",
  "No stored PostgreSQL passwords",
  "No automatic reference-data DML",
  "Release artifacts are review-only",
];

export const intendedUsers = [
  {
    role: "Application developers",
    need: "Review database structure and reference-data changes beside application code.",
    value:
      "Repository-managed database state makes changes easier to inspect, discuss, and include in pull-request workflows.",
  },
  {
    role: "Database engineers",
    need: "Understand exactly how a target PostgreSQL database differs from repository desired state.",
    value:
      "Object Diff, Data Diff, and explicit state classifications expose missing, different, database-only, and in-sync state.",
  },
  {
    role: "Technical leads",
    need: "Reduce dependence on undocumented manual database changes and one-off release scripts.",
    value:
      "Review plans and repository state provide a clearer handoff between development, review, and database execution.",
  },
  {
    role: "Regulated or audit-sensitive teams",
    need: "Preserve clearer evidence of intended database state and reviewed release artifacts.",
    value:
      "Git-managed files and review-only artifacts improve traceability without claiming regulatory compliance certification.",
  },
];

export const privateBetaScope = [
  "PostgreSQL",
  "Windows",
  "Local developer workflow",
  "Git repository required",
  "Review-only release artifacts",
  "Access by request",
];
