export const workflowModes = [
  {
    stateType: "Schema",
    workflows: [
      {
        title: "Schema Compare: Database to Repository",
        direction: "Database to Repository",
        source: "PostgreSQL database",
        target: "Git repository",
        purpose:
          "Inspect supported PostgreSQL objects and write selected objects into durable repository files.",
        output: "Repository-managed database object files",
        safety:
          "Repository file writes only. No database mutation. No automatic Git operations.",
      },
      {
        title: "Schema Compare: Repository to Database",
        direction: "Repository to Database",
        source: "Git repository desired state",
        target: "PostgreSQL database",
        purpose:
          "Compare repository-managed objects against a target PostgreSQL database, inspect differences, build a release plan, and generate supported review-only SQL artifacts.",
        output: "Comparison results and review-only release artifacts",
        safety:
          "Read-only database comparison. No direct apply. No generated SQL execution.",
      },
    ],
  },
  {
    stateType: "Reference data",
    workflows: [
      {
        title: "Reference Data Compare: Database to Repository",
        direction: "Database to Repository",
        source: "PostgreSQL database",
        target: "Git repository",
        purpose:
          "Choose reference-data tables, define key, versioned, ignored, and masked columns, preview generated YAML, and write approved files into the repository.",
        output: "Reference-data configuration and YAML files",
        safety:
          "Typed confirmation for repository writes. No database mutation. No automatic Git operations.",
      },
      {
        title: "Reference Data Compare: Repository to Database",
        direction: "Repository to Database",
        source: "Repository-managed YAML",
        target: "PostgreSQL database",
        purpose:
          "Compare repository-managed reference-data rows against PostgreSQL and inspect repository-only, database-only, different, and in-sync rows.",
        output: "Row-level Data Diff",
        safety:
          "Read-only comparison. No INSERT, UPDATE, DELETE, MERGE, or direct data apply in the current Private Beta scope.",
      },
    ],
  },
];

export const postgresqlCapabilityGroups = [
  {
    category: "Structure",
    objects: [
      "Schemas",
      "Extensions",
      "Enums",
      "Sequences",
      "Tables",
      "Indexes",
    ],
  },
  {
    category: "Query and derived objects",
    objects: ["Views", "Materialized views"],
  },
  {
    category: "Constraints",
    objects: [
      "Primary keys",
      "Unique constraints",
      "Foreign keys",
      "Check constraints",
    ],
  },
  {
    category: "Programmability",
    objects: ["Regular functions", "Triggers"],
  },
  {
    category: "Security",
    objects: ["Grants", "Row-level security policies"],
  },
  {
    category: "Data",
    objects: ["Reference data"],
  },
];

export const postgresqlScopeLimitations =
  "Current Private Beta scope does not yet include procedures, aggregates, window functions, default privileges, database-level or column-level privileges, ownership changes, or role membership grants.";

export const safetyCommitments = [
  {
    title: "Database execution stays outside DbState",
    summary:
      "DbState does not directly apply generated SQL or execute generated release artifacts.",
    detail:
      "Users review and execute approved SQL using their normal database release process outside DbState.",
    label: "controlled handoff",
  },
  {
    title: "Destructive changes remain manual-review cases",
    summary:
      "Destructive SQL is not generated by default, and database-only or changed objects may remain manual-review cases.",
    detail:
      "DbState avoids pretending that every database difference can be safely automated.",
    label: "manual review",
  },
  {
    title: "Repository and Git changes remain explicit",
    summary:
      "Repository file writes occur only through explicit user workflows.",
    detail:
      "DbState does not automatically add, commit, push, pull, fetch, or tag. The user retains control of Git history and release handoff.",
    label: "user remains in control",
  },
];

export const safetyTechnicalBoundaries = [
  "No direct database apply",
  "No generated SQL execution",
  "No destructive SQL generation by default",
  "No automatic Git add, commit, push, pull, fetch, or tag",
  "No stored PostgreSQL passwords",
  "No automatic reference-data DML",
  "Release artifacts are review-only",
];

export const intendedUsers = [
  {
    role: "Application developers",
    need: "Review database structure and reference-data changes beside application code.",
    value:
      "Repository-managed database state makes changes easier to inspect, discuss, and include in pull-request workflows.",
  },
  {
    role: "Database engineers",
    need: "Understand exactly how a target PostgreSQL database differs from repository desired state.",
    value:
      "Object Diff, Data Diff, and explicit state classifications expose missing, different, database-only, and in-sync state.",
  },
  {
    role: "Technical leads",
    need: "Reduce dependence on undocumented manual database changes and one-off release scripts.",
    value:
      "Review plans and repository state provide a clearer handoff between development, review, and database execution.",
  },
  {
    role: "Regulated or audit-sensitive teams",
    need: "Preserve clearer evidence of intended database state and reviewed release artifacts.",
    value:
      "Git-managed files and review-only artifacts improve traceability without claiming regulatory compliance certification.",
  },
];

export const privateBetaScope = [
  "PostgreSQL",
  "Windows",
  "Local developer workflow",
  "Git repository required",
  "Review-only release artifacts",
  "Access by request",
];
